// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "ttsEngine.current": string;
      "ttsEngine.reloadTries": number;
      "newItemBehaviour": string;
      "general.reloadTabs": boolean;
      "webSpeech.voice": string;
      "webSpeech.pitch": number;
      "webSpeech.rate": number;
      "webSpeech.volume": number;
      "shortcuts.speak": string;
      "shortcuts.pause": string;
      "shortcuts.cancel": string;
      "shortcuts.cycleFavourite": string;
      "shortcuts.speedUp": string;
      "shortcuts.speedDown": string;
      "shortcuts.swapLibraryItem": string;
      "shortcuts.swapAnnotation": string;
      "shortcuts.swapSpeakSelection": string;
      "subs.removeParenCitations": boolean;
      "subs.removeNumericCitations": boolean;
      "subs.removeEmails": boolean;
      "subs.removeURLs": boolean;
      "subs.fixGreekLetters": boolean;
      "subs.customSubs": string;
      "favouritesList": string;
    };
  }
}
