name: Feature Request
description: Request a new feature or enhancement!
title: "[FR]: "
labels: ["type:feature"]
assignees: 
  - ImperialSquid
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same feature request.
          required: true
        - label: I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
          required: true
        - label: I have read through the [changelog](https://github.com/ImperialSquid/zotero-zotts/blob/main/docs/CHANGELOG.md) to confirm the feature doesn't already exist. 
          required: true
        - label: I have read through the [roadmap](https://github.com/ImperialSquid/zotero-zotts/blob/main/docs/ROADMAP.md) to confirm the feature isn't already planned. (Note - you can still open a feature request if you think the feature should have a higher priority/should be implemented differently/etc!)
          required: true
        - label: I have described the feature request with as much detail as possible.
          required: true
        - label: This request contains only one single feature, **not** a list of multiple (related) features.
          required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature or improvement you want
      description: Try to be as specific as possible. If you're a technically knowledged user you can also give suggestions for how this would be implemented.
  - type: textarea
    id: reason
    attributes:
      label: Why should this be added?
      description: What problem does the feature solve? In what use-cases is the feature needed?
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Drawings / Technical details
      description: If your request is about (or includes) changing or extending the UI, describe what the UI would look like and how the user would interact with it.